#!/bin/bash

for dir in * ;do
    if [ -e $dir/stats.json ] ;then
    stats=`cat $dir/stats.json | sed -e 's/\":,/\":-1,/g'`
    columns=".TIMESTAMP, .FINAL_RESULT, .TORTURE_FAILED, .RUNNING_CPU_MAX, .RUNNING_CPU_AVG, .FINAL_CPU_AVG, .FINAL_CPU_MAX, .RUNNING_THREAD_MAX, .RUNNING_THREAD_AVG, .FINAL_THREAD_MAX, .FINAL_THREAD_AVG, .RUNNING_BITRATE_MAX, .RUNNING_BITRATE_AVG, .FINAL_BITRATE_MAX, .FINAL_BITRATE_AVG, .JVB_FINAL_STACK_THREAD_COUNT, .JICOFO_FINAL_STACK_THREAD_COUNT, .JVB_RUNNING_STACK_THREAD_COUNT, .JICOFO_RUNNING_STACK_THREAD_COUNT, .JVB_RUNNING_HEAP_SIZE, .JVB_FINAL_HEAP_SIZE, .JICOFO_RUNNING_HEAP_SIZE, .JICOFO_FINAL_HEAP_SIZE, .JICOFO_LOGFILE_SIZE, .JVB_LOGFILE_SIZE, .JVB_LOGFILE_LINECOUNT, .JICOFO_LOGFILE_LINECOUNT, .JVB_RUNNING_LSOF_LINECOUNT, .JVB_FINAL_LSOF_LINECOUNT, .JICOFO_RUNNING_LSOF_LINECOUNT, .JICOFO_FINAL_LSOF_LINECOUNT, .INSTANCE_TYPE, .JVB_VERSION, .JICOFO_VERSION, .JITSI_MEET_VERSION, .BUILD, .PIPELINE_BUILD_NUMBER"

    echo -ne "$dir\t"
    echo "$columns" | tr -d , | tr ' ' '\t'
    echo -ne "$dir\t"
    echo $stats | jq "$columns"| tr '\n' '\t'
    echo
    fi
done 
